language: cpp
sudo: required
dist: trusty
compiler:
  - gcc
  - clang
before_install:
  - |-
    if [ "$CXX" = "g++" ]; then
        pip install --user pyyaml cpp-coveralls
        export CXXFLAGS=--coverage
        export LDFLAGS=--coverage
    fi
script:
  - make && make test
after_success:
  - if [ "$CXX" = "g++" ]; then coveralls; fi
